inherit_from:
  - .rubocop_airbnb.yml
Rails:
  Enabled: true
LineLength:
  Max: 180
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
    
Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'spec/rails_helper.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
