name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev
        bundle install

    - name: Set up database
      run: |
        sudo service mysql start
        mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;' -u root --password=password

    - name: Run RSpec
      env:
        MYSQL_HOST: mysql
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: test_db
      run: |
        bundle exec rake db:migrate RAILS_ENV=test
        bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Heroku Container Registry
      run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username ${{ secrets.HEROKU_EMAIL }} --password-stdin registry.heroku.com

    - name: Build and push Docker Image to Heroku
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release Docker Image to Heroku
      run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
