name: CI/CD Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rails_app_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h mysql -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t ending-note-tkr .

    - name: Run RSpec Tests
      run: |
        docker run --network host -e DATABASE_URL=${{ secrets.TEST_DATABASE_URL }} ending-note-tkr bundle exec rspec

    - name: Run RuboCop
      run: docker run ending-note-tkr bundle exec rubocop

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Heroku Container Registry
      run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username ${{ secrets.HEROKU_EMAIL }} --password-stdin registry.heroku.com

    - name: Build and push Docker Image to Heroku
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release Docker Image to Heroku
      run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
